concurrent = 1
check_interval = 0
connection_max_age = "15m0s"
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "dind-runner"
  url = "https://git.ita.wat.edu.pl"
  id = 25
  token = "glrt-vyAkqLw-bR-1XqC30MC5LW86MQpwOjU5CnQ6Mwp1OjJ1EQ.01.1a1n9cgle"
  token_obtained_at = 2025-11-13T20:31:41Z
  token_expires_at = 0001-01-01T00:00:00Z
  tls-ca-file = "/usr/local/share/ca-certificates/ca.local.crt"
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "dind-runner"
  url = "https://git.ita.wat.edu.pl"
  id = 25
  token = "glrt-vyAkqLw-bR-1XqC30MC5LW86MQpwOjU5CnQ6Mwp1OjJ1EQ.01.1a1n9cgle"
  token_obtained_at = 2025-11-13T20:37:37Z
  token_expires_at = 0001-01-01T00:00:00Z
  tls-ca-file = "/usr/local/share/ca-certificates/ca.local.crt"
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "gitlab-runner-server"
  url = "https://git.ita.wat.edu.pl"
  id = 25
  token = "glrt-vyAkqLw-bR-1XqC30MC5LW86MQpwOjU5CnQ6Mwp1OjJ1EQ.01.1a1n9cgle"
  token_obtained_at = 2025-11-13T20:46:07Z
  token_expires_at = 0001-01-01T00:00:00Z
  tls-ca-file = "/usr/local/share/ca-certificates/ca.local.crt"
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "gitlab-runner-server"
  url = "https://git.ita.wat.edu.pl"
  id = 25
  token = "glrt-vyAkqLw-bR-1XqC30MC5LW86MQpwOjU5CnQ6Mwp1OjJ1EQ.01.1a1n9cgle"
  token_obtained_at = 2025-11-13T20:49:53Z
  token_expires_at = 0001-01-01T00:00:00Z
  tls-ca-file = "/usr/local/share/ca-certificates/ca.local.crt"
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "gitlab-runner-server"
  url = "https://git.ita.wat.edu.pl"
  id = 25
  token = "glrt-vyAkqLw-bR-1XqC30MC5LW86MQpwOjU5CnQ6Mwp1OjJ1EQ.01.1a1n9cgle"
  token_obtained_at = 2025-11-13T21:03:00Z
  token_expires_at = 0001-01-01T00:00:00Z
  tls-ca-file = "/usr/local/share/ca-certificates/ca.local.crt"
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0

[[runners]]
  name = "gitlab-runner-server"
  url = "https://git.ita.wat.edu.pl"
  id = 25
  token = "glrt-vyAkqLw-bR-1XqC30MC5LW86MQpwOjU5CnQ6Mwp1OjJ1EQ.01.1a1n9cgle"
  token_obtained_at = 2025-11-15T23:28:06Z
  token_expires_at = 0001-01-01T00:00:00Z
  tls-ca-file = "/usr/local/share/ca-certificates/ca.local.crt"
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
    [runners.cache.s3]
    [runners.cache.gcs]
    [runners.cache.azure]
  [runners.docker]
    tls_verify = false
    image = "docker:latest"
    privileged = true
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0
    network_mtu = 0
