version: "3.8"

services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    container_name: gitlab-runner
    restart: always
    privileged: true  # wymagane dla DinD
    volumes:
      - ./config:/etc/gitlab-runner
      - ./cache:/cache
      - ./config/ca.local.crt:/usr/local/share/ca-certificates/ca.local.crt:ro
